# **<div align="center">TERGET DEFINITION</div>**

Subtitle

In [60]:
import pandas as pd
import numpy as np

## **Initial Configuration**

In [61]:
HORIZONS = {
    "short": 7,
    "medium": 21,
    "long": 50
}

CRYPTO_NAMES = [
    "bitcoin",
    "ethereum",
    "tether",
    "binancecoin",
    "usd-coin",
    "ripple"
]

DATA_PATH = "../data/processed/"

In [62]:
def classify_trend(value, p10, p30, p70, p90):
    if pd.isna(value):
        return np.nan

    if value <= p10:
        return -2
    elif value <= p30:
        return -1
    elif value <= p70:
        return 0
    elif value <= p90:
        return 1
    else:
        return 2

## **Import dataset**

In [63]:
dfs = {}

for crypto in CRYPTO_NAMES:
    path = f"{DATA_PATH}{crypto}.csv"
    
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    df = df.set_index("date", drop=False).sort_index()
    
    dfs[crypto] = df

    print(
        f"{crypto}: "
        f"{len(df)} observations | "
        f"{df.index.min().date()} -> {df.index.max().date()}"
    )

bitcoin: 281 observations | 2025-02-05 -> 2025-11-12
ethereum: 241 observations | 2025-02-05 -> 2025-10-03
tether: 281 observations | 2025-02-05 -> 2025-11-12
binancecoin: 240 observations | 2025-02-05 -> 2025-10-02
usd-coin: 280 observations | 2025-02-06 -> 2025-11-12
ripple: 235 observations | 2025-02-07 -> 2025-09-29

In [64]:
for crypto, df in dfs.items():
    print(f"\n{crypto}")
    display(df.head())

bitcoin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,1.0,97864.0,1.940960e+12,6.365740e+10,2025-02-05
2025-02-06,1.0,99038.0,1.960400e+12,4.243940e+10,2025-02-06
2025-02-07,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-07
2025-02-08,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-08
2025-02-09,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-09

ethereum

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,2.0,2780.50,3.352540e+11,4.421130e+10,2025-02-05
2025-02-06,2.0,2825.73,3.408410e+11,3.054070e+10,2025-02-06
2025-02-07,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-07
2025-02-08,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-08
2025-02-09,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-09

tether

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,3.0,1.0,1.405310e+11,1.073240e+11,2025-02-05
2025-02-06,3.0,1.0,1.412260e+11,8.110920e+10,2025-02-06
2025-02-07,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-07
2025-02-08,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-08
2025-02-09,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-09

binancecoin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,4.0,571.03,8.327530e+10,1.241400e+09,2025-02-05
2025-02-06,4.0,580.05,8.457820e+10,4.711890e+08,2025-02-06
2025-02-07,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-07
2025-02-08,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-08
2025-02-09,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-09

usd-coin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-06,5.0,1.00000,5.554900e+10,1.122790e+10,2025-02-06
2025-02-07,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-07
2025-02-08,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-08
2025-02-09,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-09
2025-02-10,5.0,0.99995,5.627930e+10,8.631850e+09,2025-02-10

ripple

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-07,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-07
2025-02-08,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-08
2025-02-09,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-09
2025-02-10,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-10
2025-02-11,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-11

## **1. Calculate price target for each horizon**

In [65]:
for crypto, df in dfs.items():

    for horizon_name, horizon in HORIZONS.items():

        df[f"target_price_{horizon_name}"] = (
            df["price_usd"].shift(-horizon)
        )

## **2. Calculate future returns**

In [67]:
for crypto, df in dfs.items():
    
    for name, horizon in HORIZONS.items():
        df[f"future_return_{name}"] = (
            df["price_usd"].shift(-horizon)
            / df["price_usd"]
            - 1
        )

In [68]:
dfs["bitcoin"][
    [
        "price_usd",
        "target_price_short",
        "target_price_medium",
        "target_price_long",
        "future_return_short",
        "future_return_medium",
        "future_return_long"
    ]
].head(10)

,price_usd,target_price_short,target_price_medium,target_price_long,future_return_short,future_return_medium,future_return_long
date,,,,,,,
2025-02-05,97864.0,95933.0,89191.0,87325.0,-0.019731,-0.088623,-0.107690
2025-02-06,99038.0,96199.0,86978.0,84936.0,-0.028666,-0.121771,-0.142390
2025-02-07,97683.0,97032.0,79806.0,84936.0,-0.006664,-0.183010,-0.130494
2025-02-08,97683.0,97032.0,79806.0,84936.0,-0.006664,-0.183010,-0.130494
2025-02-09,97683.0,97032.0,79806.0,81489.0,-0.006664,-0.183010,-0.165781
2025-02-10,97676.0,96124.0,92529.0,84489.0,-0.015889,-0.052695,-0.135008
2025-02-11,98094.0,95669.0,83902.0,85029.0,-0.024721,-0.144678,-0.133189
2025-02-12,95933.0,96302.0,89845.0,83450.0,0.003846,-0.063461,-0.130122
2025-02-13,96199.0,97408.0,91059.0,84610.0,0.012568,-0.053431,-0.120469
2025-02-14,97032.0,98634.0,89086.0,84610.0,0.016510,-0.081891,-0.128020