# **<div align="center">TERGET DEFINITION</div>**

Subtitle

In [1]:
import pandas as pd
import numpy as np

## **Initial Configuration**

In [2]:
HORIZONS = {
    "short": 7,
    "medium": 21,
    "long": 50
}

CRYPTO_NAMES = [
    "bitcoin",
    "ethereum",
    "tether",
    "binancecoin",
    "usd-coin",
    "ripple"
]

DATA_PATH = "../data/processed/"

In [3]:
def classify_trend(value, p10, p30, p70, p90):
    if pd.isna(value):
        return np.nan

    if value <= p10:
        return -2
    elif value <= p30:
        return -1
    elif value <= p70:
        return 0
    elif value <= p90:
        return 1
    else:
        return 2

In [23]:
def classify_ratio(ratio):
    if pd.isna(ratio):
        return np.nan
    elif ratio <= -2:
        return -2
    elif ratio <= -1:
        return -1
    elif ratio < 1:
        return 0
    elif ratio < 2:
        return 1
    else:
        return 2

## **Import dataset**

In [4]:
dfs = {}

for crypto in CRYPTO_NAMES:
    path = f"{DATA_PATH}{crypto}.csv"
    
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    df = df.set_index("date", drop=False).sort_index()
    
    dfs[crypto] = df

    print(
        f"{crypto}: "
        f"{len(df)} observations | "
        f"{df.index.min().date()} -> {df.index.max().date()}"
    )

bitcoin: 281 observations | 2025-02-05 -> 2025-11-12
ethereum: 241 observations | 2025-02-05 -> 2025-10-03
tether: 281 observations | 2025-02-05 -> 2025-11-12
binancecoin: 240 observations | 2025-02-05 -> 2025-10-02
usd-coin: 280 observations | 2025-02-06 -> 2025-11-12
ripple: 235 observations | 2025-02-07 -> 2025-09-29

In [5]:
for crypto, df in dfs.items():
    print(f"\n{crypto}")
    display(df.head())

bitcoin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,1.0,97864.0,1.940960e+12,6.365740e+10,2025-02-05
2025-02-06,1.0,99038.0,1.960400e+12,4.243940e+10,2025-02-06
2025-02-07,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-07
2025-02-08,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-08
2025-02-09,1.0,97683.0,1.932660e+12,4.612790e+10,2025-02-09

ethereum

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,2.0,2780.50,3.352540e+11,4.421130e+10,2025-02-05
2025-02-06,2.0,2825.73,3.408410e+11,3.054070e+10,2025-02-06
2025-02-07,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-07
2025-02-08,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-08
2025-02-09,2.0,2753.45,3.318870e+11,3.019830e+10,2025-02-09

tether

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,3.0,1.0,1.405310e+11,1.073240e+11,2025-02-05
2025-02-06,3.0,1.0,1.412260e+11,8.110920e+10,2025-02-06
2025-02-07,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-07
2025-02-08,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-08
2025-02-09,3.0,1.0,1.414070e+11,6.782090e+10,2025-02-09

binancecoin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-05,4.0,571.03,8.327530e+10,1.241400e+09,2025-02-05
2025-02-06,4.0,580.05,8.457820e+10,4.711890e+08,2025-02-06
2025-02-07,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-07
2025-02-08,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-08
2025-02-09,4.0,586.11,8.556300e+10,1.075490e+09,2025-02-09

usd-coin

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-06,5.0,1.00000,5.554900e+10,1.122790e+10,2025-02-06
2025-02-07,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-07
2025-02-08,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-08
2025-02-09,5.0,0.99999,5.574810e+10,1.090440e+10,2025-02-09
2025-02-10,5.0,0.99995,5.627930e+10,8.631850e+09,2025-02-10

ripple

,cryptocurrency_id,price_usd,market_cap,volume,date
date,,,,,
2025-02-07,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-07
2025-02-08,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-08
2025-02-09,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-09
2025-02-10,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-10
2025-02-11,6.0,2.42,1.399750e+11,6.647130e+09,2025-02-11

## **1. Calculate price target for each horizon**

In [6]:
for crypto, df in dfs.items():

    for horizon_name, horizon in HORIZONS.items():

        df[f"target_price_{horizon_name}"] = (
            df["price_usd"].shift(-horizon)
        )

## **2. Calculate future returns**

In [7]:
for crypto, df in dfs.items():
    
    for name, horizon in HORIZONS.items():
        df[f"future_return_{name}"] = (
            df["price_usd"].shift(-horizon)
            / df["price_usd"]
            - 1
        )

In [13]:
dfs["bitcoin"][
    [
        "price_usd",
        "target_price_short",
        "target_price_medium",
        "target_price_long",
        "future_return_short",
        "future_return_medium",
        "future_return_long"
    ]
].head(10)

,price_usd,target_price_short,target_price_medium,target_price_long,future_return_short,future_return_medium,future_return_long
date,,,,,,,
2025-02-05,97864.0,95933.0,89191.0,87325.0,-0.019731,-0.088623,-0.107690
2025-02-06,99038.0,96199.0,86978.0,84936.0,-0.028666,-0.121771,-0.142390
2025-02-07,97683.0,97032.0,79806.0,84936.0,-0.006664,-0.183010,-0.130494
2025-02-08,97683.0,97032.0,79806.0,84936.0,-0.006664,-0.183010,-0.130494
2025-02-09,97683.0,97032.0,79806.0,81489.0,-0.006664,-0.183010,-0.165781
2025-02-10,97676.0,96124.0,92529.0,84489.0,-0.015889,-0.052695,-0.135008
2025-02-11,98094.0,95669.0,83902.0,85029.0,-0.024721,-0.144678,-0.133189
2025-02-12,95933.0,96302.0,89845.0,83450.0,0.003846,-0.063461,-0.130122
2025-02-13,96199.0,97408.0,91059.0,84610.0,0.012568,-0.053431,-0.120469
2025-02-14,97032.0,98634.0,89086.0,84610.0,0.016510,-0.081891,-0.128020

## **3. Calculate daily returns**

In [10]:
for crypto, df in dfs.items():
    df["return_1d"] = df["price_usd"].pct_change()

## **4. Horizon volatility**

In [11]:
for crypto, df in dfs.items():

    for horizon_name, horizon in HORIZONS.items():

        df[f"volatility_{horizon_name}"] = (
            df["return_1d"]
            .rolling(window=horizon)
            .std()
            * np.sqrt(horizon)
        )

In [12]:
dfs["bitcoin"][
    [
        "price_usd",
        "return_1d",
        "volatility_short",
        "volatility_medium",
        "volatility_long"
    ]
].tail(15)

,price_usd,return_1d,volatility_short,volatility_medium,volatility_long
date,,,,,
2025-10-29,120434.0,0.000000,0.000000,0.000000,0.066310
2025-10-30,120434.0,0.000000,0.000000,0.000000,0.065903
2025-10-31,120434.0,0.000000,0.000000,0.000000,0.064290
2025-11-01,120434.0,0.000000,0.000000,0.000000,0.063816
2025-11-02,120434.0,0.000000,0.000000,0.000000,0.063116
2025-11-03,120434.0,0.000000,0.000000,0.000000,0.063106
2025-11-04,120434.0,0.000000,0.000000,0.000000,0.062035
2025-11-05,120434.0,0.000000,0.000000,0.000000,0.061859
2025-11-06,120434.0,0.000000,0.000000,0.000000,0.061426
2025-11-07,120434.0,0.000000,0.000000,0.000000,0.061051
2025-11-08,120434.0,0.000000,0.000000,0.000000,0.060617
2025-11-09,120434.0,0.000000,0.000000,0.000000,0.060183
2025-11-10,120434.0,0.000000,0.000000,0.000000,0.060158
2025-11-11,120434.0,0.000000,0.000000,0.000000,0.053868
2025-11-12,104757.0,-0.130171,0.130171,0.130171,0.142116

In [14]:
volatility_summary = []

for crypto, df in dfs.items():

    for horizon in HORIZONS:

        column = f"volatility_{horizon}"

        stats = df[column].dropna().describe()

        volatility_summary.append({
            "crypto": crypto,
            "horizon": horizon,
            "count": int(stats["count"]),
            "mean": stats["mean"],
            "median": stats["50%"],
            "p25": stats["25%"],
            "p75": stats["75%"],
            "max": stats["max"]
        })

volatility_summary_df = pd.DataFrame(volatility_summary)

volatility_summary_df[
    ["mean", "median", "p25", "p75", "max"]
] = volatility_summary_df[
    ["mean", "median", "p25", "p75", "max"]
].round(6)

display(volatility_summary_df)

,crypto,horizon,count,mean,median,p25,p75,max
0,bitcoin,short,274,0.042904,0.033332,0.022398,0.052515,0.232702
1,bitcoin,medium,260,0.085088,0.070266,0.060229,0.092617,0.250070
2,bitcoin,long,231,0.132199,0.115027,0.096174,0.161760,0.288757
3,ethereum,short,234,0.096925,0.090079,0.068168,0.117136,0.230695
4,ethereum,medium,220,0.183062,0.169873,0.149364,0.230328,0.263055
5,ethereum,long,191,0.290772,0.280140,0.259018,0.313995,0.373840
6,tether,short,274,0.000381,0.000183,0.000000,0.000538,0.002168
7,tether,medium,260,0.000855,0.000727,0.000255,0.001449,0.002511
8,tether,long,231,0.001592,0.001450,0.001038,0.002126,0.003229
9,binancecoin,short,233,0.060016,0.056564,0.033280,0.084469,0.140580
10,binancecoin,medium,219,0.106870,0.098645,0.074142,0.134698,0.193852
11,binancecoin,long,190,0.161844,0.158600,0.124054,0.183308,0.248945
12,usd-coin,short,273,0.000117,0.000111,0.000055,0.000174,0.000348
13,usd-coin,medium,259,0.000220,0.000239,0.000157,0.000289,0.000410
14,usd-coin,long,230,0.000368,0.000378,0.000322,0.000412,0.000526
15,ripple,short,228,0.040333,0.000000,0.000000,0.076829,0.180514
16,ripple,medium,214,0.088274,0.082645,0.000000,0.140158,0.254838
17,ripple,long,185,0.159223,0.158513,0.074890,0.226451,0.301356

## **5. Volatility ratio**

In [15]:
for crypto, df in dfs.items():

    for horizon in HORIZONS:

        df[f"volatility_ratio_{horizon}"] = (
            df[f"future_return_{horizon}"]
            / df[f"volatility_{horizon}"]
        )

In [16]:
for crypto, df in dfs.items():

    ratio_columns = [
        f"volatility_ratio_{horizon}"
        for horizon in HORIZONS
    ]

    df[ratio_columns] = (
        df[ratio_columns]
        .replace([np.inf, -np.inf], np.nan)
    )

In [20]:
display(
    dfs["bitcoin"][
        [
            "future_return_short",
            "volatility_short",
            "volatility_ratio_short",
            "future_return_medium",
            "volatility_medium",
            "volatility_ratio_medium",
            "future_return_long",
            "volatility_long",
            "volatility_ratio_long"
        ]
    ]
    .dropna()
    .head(15)
)

,future_return_short,volatility_short,volatility_ratio_short,future_return_medium,volatility_medium,volatility_ratio_medium,future_return_long,volatility_long,volatility_ratio_long
date,,,,,,,,,
2025-03-27,-0.044374,0.050365,-0.881062,-0.041764,0.097210,-0.429623,0.187896,0.255738,0.734719
2025-03-28,-0.003838,0.057450,-0.066809,-0.014811,0.098589,-0.150231,0.221308,0.256622,0.862387
2025-03-29,-0.003838,0.057450,-0.066809,-0.014811,0.098589,-0.150231,0.221308,0.256375,0.863219
2025-03-30,-0.003838,0.057450,-0.066809,-0.014811,0.098589,-0.150231,0.212466,0.256375,0.828730
2025-03-31,-0.061321,0.046915,-1.307068,0.073593,0.074942,0.981991,0.292592,0.259222,1.128728
2025-04-01,-0.064375,0.066823,-0.963367,0.047580,0.083257,0.571482,0.257217,0.262250,0.980807
2025-04-02,-0.089581,0.065905,-1.359243,0.103694,0.083170,1.246768,0.301627,0.262312,1.149875
2025-04-03,-0.018238,0.067181,-0.271481,0.107741,0.085222,1.264246,0.333170,0.262068,1.271309
2025-04-04,-0.021841,0.064633,-0.337928,0.108072,0.086280,1.252572,0.314892,0.262516,1.199515
2025-04-05,-0.021841,0.064633,-0.337928,0.108072,0.086280,1.252572,0.314892,0.262303,1.200487
2025-04-06,-0.021841,0.064633,-0.337928,0.108072,0.086280,1.252572,0.297683,0.262303,1.134883
2025-04-07,0.106351,0.111567,0.953246,0.238247,0.129723,1.836589,0.435640,0.278573,1.563831
2025-04-08,0.083061,0.110020,0.754969,0.201214,0.134815,1.492518,0.374953,0.281009,1.334310
2025-04-09,0.080944,0.109022,0.742454,0.226076,0.135193,1.672246,0.401721,0.281556,1.426790
2025-04-10,0.021360,0.129311,0.165185,0.158493,0.147499,1.074532,0.286935,0.288118,0.995895

## **6. Ratio summarize**

In [21]:
ratio_summary = []

for crypto, df in dfs.items():

    for horizon in HORIZONS:

        column = f"volatility_ratio_{horizon}"

        stats = (
            df[column]
            .dropna()
            .describe(
                percentiles=[
                    0.05,
                    0.10,
                    0.25,
                    0.50,
                    0.75,
                    0.90,
                    0.95
                ]
            )
        )

        ratio_summary.append({
            "crypto": crypto,
            "horizon": horizon,
            "count": int(stats["count"]),
            "mean": stats["mean"],
            "p05": stats["5%"],
            "p10": stats["10%"],
            "p25": stats["25%"],
            "median": stats["50%"],
            "p75": stats["75%"],
            "p90": stats["90%"],
            "p95": stats["95%"],
            "min": stats["min"],
            "max": stats["max"]
        })

ratio_summary_df = pd.DataFrame(ratio_summary)

In [22]:
numeric_columns = [
    "mean",
    "p05",
    "p10",
    "p25",
    "median",
    "p75",
    "p90",
    "p95",
    "min",
    "max"
]

ratio_summary_df[numeric_columns] = (
    ratio_summary_df[numeric_columns].round(3)
)

display(ratio_summary_df)

,crypto,horizon,count,mean,p05,p10,p25,median,p75,p90,p95,min,max
0,bitcoin,short,240,0.468,-1.662,-1.287,-0.381,0.151,0.875,2.881,3.734,-8.785,22.043
1,bitcoin,medium,239,0.357,-0.878,-0.459,-0.156,0.226,0.969,1.460,1.816,-5.355,2.661
2,bitcoin,long,181,0.512,-0.514,-0.281,0.245,0.622,0.907,1.099,1.200,-0.775,1.564
3,ethereum,short,227,0.476,-1.884,-1.211,-0.513,0.124,0.642,2.420,2.945,-6.471,15.854
4,ethereum,medium,199,0.551,-0.959,-0.601,-0.250,0.127,1.206,2.372,3.005,-1.677,3.707
5,ethereum,long,141,1.282,-0.076,0.089,0.671,1.301,1.728,2.556,2.772,-0.282,3.379
6,tether,short,204,-0.163,-2.149,-1.127,-0.117,0.000,0.225,1.000,1.163,-42.000,53.555
7,tether,medium,235,0.080,-0.507,-0.279,0.000,0.000,0.055,0.486,0.618,-1.586,4.114
8,tether,long,181,0.013,-0.427,-0.197,0.000,0.000,0.033,0.245,0.665,-1.154,0.980
9,binancecoin,short,226,0.545,-1.160,-0.886,-0.297,0.119,1.195,2.486,3.886,-4.669,8.310
10,binancecoin,medium,198,0.715,-0.538,-0.470,0.087,0.534,1.079,2.165,2.462,-0.777,4.895
11,binancecoin,long,140,1.181,0.064,0.151,0.422,1.160,1.882,2.472,2.596,-0.142,3.205
12,usd-coin,short,238,0.038,-1.491,-1.042,-0.391,-0.018,0.354,0.961,1.912,-6.127,8.784
13,usd-coin,medium,238,-0.044,-1.159,-0.692,-0.267,0.000,0.286,0.579,0.690,-2.109,1.099
14,usd-coin,long,180,-0.120,-0.529,-0.487,-0.316,-0.151,0.033,0.253,0.356,-0.746,0.591
15,ripple,short,96,0.429,-2.142,-1.330,-0.403,0.000,0.529,1.841,2.341,-8.352,27.095
16,ripple,medium,122,0.185,-1.616,-0.941,-0.358,0.000,0.156,0.671,5.485,-1.616,6.488
17,ripple,long,120,1.600,-0.545,-0.165,0.211,0.561,3.195,4.378,4.433,-0.778,5.691

In [24]:
for crypto, df in dfs.items():
    for horizon in HORIZONS:
        ratio_col = f"volatility_ratio_{horizon}"
        target_col = f"target_trend_{horizon}"

        df[target_col] = df[ratio_col].apply(classify_ratio)